# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: "%env(APP_SECRET)%"
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true
    default_locale: fr

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        enabled: true
        handler_id: null # session.handler.native_file
        name: "HandyMirror_Shop"
        sid_bits_per_character: 6
        cookie_secure: false
        cookie_samesite: lax
        cookie_lifetime: 604800 # 1 semaine (3600 * 24 * 7)
        gc_maxlifetime: 604800 # 1 semaine (3600 * 24 * 7)
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
