controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
send_email:
    path: /email
    controller: App\Controller\MailController::index
confirm_account:
    path: /confirm-account/{token}
    controller: App\Controller\AccountConfirmationController::confirmAccount
home:
    path: /
    controller: App\Controller\HomeController::index

